name: Execução Periódica

on:
  schedule:
    - cron: '*/15 * * * *' # Executar a cada 15 minutos e
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7 # Substitua 'x' pela versão desejada do Python

      - name: Executar código Python
        run: python raspador_emendas.py
