name: raspador_emendas

on:
  schedule:
    - cron: '0 12 * * *' # Executar todo dia às 12 am

jobs:
  raspador_emendas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Installed system dependencies
        run: |
          apt list --installed
          sudo apt purge google-chrome-stable
          sudo apt purge chromium-browser
          sudo apt install -y chromium-browser
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Execute Script
        uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_seconds: 120
          retry_wait_seconds: 600
          command: make
      - name: Commit and push if content changed
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
