name: raspador_emendas

on:
  schedule:
    # Runs each 5 min
    - cron: '5 * * * *'
jobs:
  raspador_emendas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: python raspador_emendas.py
