name: Execução Periódica

on:
  schedule:
    - cron: '*/5 * * * *' # Executar a cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: python raspador_emendas.py
