name: raspador_emendas

on:
  schedule:
    - cron: '*/2 * * * *' # Executar a cada 2 minutos

jobs:
  raspador_emendas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - run: python raspador_emendas.py
